#!/bin/bash

#[ Script ]-------------------------------------------------------------------------------------------------#
#                                                                                                           #
# tsd                                                                                                       #
#                                                                                                           #
# PT-br:                                                                                                    #
# script de init para iniciar o threadsnake como um daemon                                                  #
#                                                                                                           #
# ----------------------------                                                                              #
#                                                                                                           #
# EN:                                                                                                       #
# init script to start threadsnake as a daemon                                                              #
#                                                                                                           #
# reimlima@gmail.com                                                                                        #
# $Id: tsd,v 1 2017/07/19 reimlima Exp reimlima $                                                           #
#                                                                                                           #
#-----------------------------------------------------------------------------------------------------------#

export PATH="/bin/rm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

#[ Variables ]-----------------------------------------------------------------#

RM=$(which rm)
PS=$(which ps)
CAT=$(which cat)
AWK=$(which awk)
KILL=$(which kill)
GREP=$(which grep)
THREADSNAKE=$(which threadsnake)
SCRIPTNAME=$(basename $0)
THREADSNAKEPIDFILE="/var/run/threadsnake/threadsnake.pid"

#[ Functions ]-----------------------------------------------------------------#

exiterrorfunc(){
	EXITCODE=$(echo $@ | awk '{print $NF}')
	EXITMESSAGE=$(echo $@ | awk '{ $NF = ""; print $0}')
	echo "$EXITMESSAGE"
	if [[ $OPTION = "restart" ]]; then
		OPTION="" 
		start
	fi
	exit $EXITCODE
}

usage(){
	exiterrorfunc "Usage: $0 {start|stop|restart|status} 1"
}

start(){
	if [[ -e $THREADSNAKEPIDFILE ]] ; then # Se existe arquivo de PID
		THREADSNAKEPID=$($CAT $THREADSNAKEPIDFILE)
		THREADSNAKEPROC=$($PS -ef | $GREP threadsnake | $GREP -v $SCRIPTNAME | $GREP -v grep | $AWK '{print $2}')

		if [[ "$THREADSNAKEPID" = "$THREADSNAKEPROC" ]]; then # Se o PID no arquivo e o processo rodando sao os mesmos...
			exiterrorfunc "threadsnake is already running: [$THREADSNAKEPID] 1"
		else # senao cospe o erro
			exiterrorfunc "threadsnake is not running, but pid file exist: [$THREADSNAKEPIDFILE] 1"
		fi
	else # Se o arquivo nao existe
		THREADSNAKEPROC=$($PS -ef | $GREP threadsnake | $GREP -v $SCRIPTNAME | $GREP -v grep | $AWK '{print $2}')

		if [[ $THREADSNAKEPROC ]]; then # Se o arquivo nao existe, mas tem um processo ativo...
			exiterrorfunc "pid file $THREADSNAKEPIDFILE does not exist, but there is a process alive: [$THREADSNAKEPROC] 1"
		else # Se passou por todas excessoes acima, entao sobe o processo finalmente
			( $THREADSNAKE & )
			while [ ! -e $THREADSNAKEPIDFILE ] ; do
				continue
			done
			THREADSNAKEPID=$($CAT $THREADSNAKEPIDFILE)
			exiterrorfunc "threadsnake started: [$THREADSNAKEPID] 0"
		fi
	fi
}

stop(){
	THREADSNAKEPROC=$($PS -ef | $GREP threadsnake | $GREP -v $SCRIPTNAME | $GREP -v grep | $AWK '{print $2}')
	if [[ -e $THREADSNAKEPIDFILE ]] ; then # Se existe arquivo de PID
		THREADSNAKEPID=$($CAT $THREADSNAKEPIDFILE)
		if [[ "$THREADSNAKEPID" = "$THREADSNAKEPROC" ]]; then # Se o PID no arquivo e o processo rodando sao os mesmos...
			$KILL -9 $THREADSNAKEPID
			$RM -f $THREADSNAKEPIDFILE
			exiterrorfunc "threadsnake stopped: [$THREADSNAKEPID] 0"
		else
			exiterrorfunc "threadsnake is not running, but pid file exist: [$THREADSNAKEPIDFILE] 1"
		fi
	elif [[ $THREADSNAKEPROC ]]; then # Se existe um processo, mas nao um arquivo PID
		exiterrorfunc "there is a threadsnake process running without PID file 1"
	else # senao nao esta rodando
		exiterrorfunc "threadsnake is not running 0"
	fi
}

status(){
	THREADSNAKEPROC=$($PS -ef | $GREP threadsnake | $GREP -v $SCRIPTNAME | $GREP -v grep | $AWK '{print $2}')
	if [[ -e $THREADSNAKEPIDFILE ]] ; then # Se existe arquivo de PID
		THREADSNAKEPID=$($CAT $THREADSNAKEPIDFILE)
		if [[ "$THREADSNAKEPID" = "$THREADSNAKEPROC" ]]; then # Se o PID no arquivo e o processo rodando sao os mesmos...
			exiterrorfunc "threadsnake is running: [$THREADSNAKEPID] 0"
		else
			exiterrorfunc "threadsnake is not running, but pid file exist: [$THREADSNAKEPIDFILE] 1"
		fi
	elif [[ $THREADSNAKEPROC ]]; then # Se existe um processo, mas nao um arquivo PID
		exiterrorfunc "there is a threadsnake process running without PID file 1"
	else
		exiterrorfunc "threadsnake is not running 0"
	fi
}

restart(){
	stop
	sleep 1
	start
}

#[ Validate command line option ]----------------------------------------------#

[ $1 ] || usage
OPTION=$1

case $OPTION in
	start   ) start;   ;;
	stop    ) stop;    ;;
	restart ) restart; ;;
	status  ) status;  ;;
	*       ) usage;   ;;
esac
